chore: upgrade got to 11.8.5
electron/get pull request #225
Opened 2022-06-29 20:02 UTC by clavin

Bumps the dependency on `got` to version 11.8.5, fixing a dependabot alert. `got` also now includes its own type definitions, so the dependency on `@types/got` could be removed as well.

2022-06-29 20:04 UTC, malept requested changes
I think this is a breaking change, as it raises the minimum Node.js version?

2022-06-29 20:53 UTC, clavin commented
Ah, you're correct. The requirement for got v11 is `"node": ">=10.19.0"`, whereas this package is still `"node": ">=8.6"`. Nice catch!

2022-06-30 03:02 UTC, malept commented
A couple of things:

1. The PR title should reflect that this is a breaking change: `chore!: upgrade got to 11.8.5`
2. I think you need to re-log-into CircleCI so that the tests will run. If I had to guess it's because of the multiple-orgs-that-require-SSO problem.

2022-06-30 15:35 UTC, clavin commented
Looks like a dependency from this got version (`compress-brotli `) actually requires the min version to be `>=12`, even though `got` is itself only marked as `>=10.19`. Also have to bump the `@types/node` dependency here.

2022-07-07 16:50 UTC, malept commented
See https://github.com/electron/get/issues/224#issuecomment-1177920828, merging this change needs to be coordinated properly.

2022-08-09 02:51 UTC, BlackHole1 commented
Based on https://github.com/electron/get/pull/226#issuecomment-1208824651 discussions. I think we should just upgrade instead of waiting for `got` to release a new patch version

2022-08-09 02:59 UTC, malept commented
We're not waiting for `got` to release a new patch version.

2022-08-09 03:03 UTC, BlackHole1 commented
What are the reasons that are stopping this PR from being merged now? I want to push for this PR to be merged.

The most important reason, as I understand it so far, is the impact of the minimum node version

2022-08-09 03:13 UTC, BlackHole1 commented
If this impact is so important to us that we cannot merge this PR in a short time, is there another way, for example if we fork `got`

2022-08-10 16:37 UTC, malept approved these changes

2022-08-10 16:43 UTC, merged