fix: allow overwriting SHASUMS256 in cache
electron/get pull request #294
Opened 2024-07-11 20:09 UTC by erickzhao

Fixes https://github.com/electron/packager/issues/1552

When downloading the same version across multiple architectures at once (e.g. for a Universal macOS build), it's possible for `fs.move` to run into a race condition because the same SHASUMS256 file is being written to the cache for each arch.

This PR allows `fs.move` to overwrite previous entries specifically for the `SHASUMS256` file.

2024-07-11 20:48 UTC, erikian approved these changes
nice

2024-07-11 20:53 UTC, MarshallOfSound requested changes
I don't think this is semantically correct as it allows one download job to override the other downloads checksums in flight.

We probably want to simply not put checksum files in the cache if we're never going to use them from the cache

2024-07-11 21:36 UTC, erickzhao commented
> I don't think this is semantically correct as it allows one download job to override the other downloads checksums in flight.

Is that creating a separate race condition where we might have a limbo state where we attempt to read from SHASUMS256 mid-overwrite? Both files are otherwise be 100% identical since this is an arch/platform-agnostic SHASUMS256.txt file.

2024-07-11 21:53 UTC, dsanders11 commented
> I don't think this is semantically correct as it allows one download job to override the other downloads checksums in flight.

Isn't that the current behavior? If the file already exists it removes it before putting the new one in the cache. It's effectively already an overwrite, just one that's prone to race conditions by checking first.

2024-07-13 04:13 UTC, erickzhao commented
Regardless, going to close this in favour of #267

2024-07-13 04:13 UTC, closed without merging